name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - run: cmake -E make_directory ${{ github.workspace }}/build

      - name: configure
        shell: bash # access regardless of the host operating system
        working-directory: ${{ github.workspace }}/build
        run: cmake $GITHUB_WORKSPACE

      - name: build
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: cmake --build .
