name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: friendlyanon/setup-vcpkg@v1 # needs to be after checkout or else it's deleted
        with: 
          committish: db0473513e5dc73ec6b6f431ff05d2f398eea042
      - if: matrix.os == 'windows-latest' # Because windows is still x86 by default 
        run: $VCPKG_ROOT/vcpkg install eigen3 --triplet=x64-windows
      - if : matrix.os != 'windows-latest'
        run: $VCPKG_ROOT/vcpkg install eigen3
        
      - run: cmake -E make_directory ${{ github.workspace }}/build

      - name: configure
        shell: bash # access regardless of the host operating system
        working-directory: ${{ github.workspace }}/build
        run: |
          ls -laR $VCPKG_ROOT
          cmake $GITHUB_WORKSPACE -B build -DCMAKE_TOOLCHAIN_FILE=$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake

      - name: build
        working-directory: ${{ github.workspace }}/build
        shell: bash
        run: cmake --build .
